package com.example.smartgoprototype.di

import com.example.smartgoprototype.data.auth.AuthInterceptor
import com.example.smartgoprototype.data.auth.CognitoSessionProvider
import com.example.smartgoprototype.data.auth.SessionProvider
import com.example.smartgoprototype.data.remote.api.RoutesApi
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import okhttp3.OkHttpClient
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import javax.inject.Singleton

/**
 * Hilt module providing network-layer singletons.
 *
 * - Centralises HTTP configuration (base URL, JSON, auth headers) in one place.
 * - Makes the rest of the app depend on abstractions (e.g., RoutesApi) rather than concrete setup code.
 */
@Module
@InstallIn(SingletonComponent::class)
object NetworkModule {

    //TODO: move this to BuildConfig
    private const val BASE_URL = "https://0y1xbqkvj7.execute-api.eu-north-1.amazonaws.com/"

    /**
     * SessionProvider is separated to keep AuthInterceptor testable and to avoid coupling OkHttp to
     * the Cognito SDK directly.
     */
    @Provides
    @Singleton
    fun provideSessionProvider(): SessionProvider = CognitoSessionProvider()

    /**
     * Interceptor responsible for adding Authorization headers (if a session is available).
     *
     * Keeping this as an OkHttp interceptor ensures all Retrofit calls automatically include auth
     * without every API call site needing to remember it.
     */
    @Provides
    @Singleton
    fun provideAuthInterceptor(
        sessionProvider: SessionProvider
    ): AuthInterceptor = AuthInterceptor(sessionProvider)

    /**
     * Single OkHttpClient instance for connection pooling and consistent interceptor configuration.
     */
    @Provides
    @Singleton
    fun provideOkHttpClient(
        authInterceptor: AuthInterceptor
    ): OkHttpClient {
        return OkHttpClient.Builder()
            .addInterceptor(authInterceptor)
            .build()
    }

    /**
     * Moshi JSON instance with Kotlin reflection adapters.
     */
    @Provides
    @Singleton
    fun provideMoshi(): Moshi =
        Moshi.Builder()
            .add(KotlinJsonAdapterFactory())
            .build()

    /**
     * Retrofit configured once and injected wherever needed.
     */
    @Provides
    @Singleton
    fun provideRetrofit(
        okHttpClient: OkHttpClient,
        moshi: Moshi
    ): Retrofit {
        return Retrofit.Builder()
            .baseUrl(BASE_URL)
            .client(okHttpClient)
            .addConverterFactory(MoshiConverterFactory.create(moshi))
            .build()
    }

    /**
     * Typed API service generated by Retrofit.
     */
    @Provides
    @Singleton
    fun provideRoutesApi(retrofit: Retrofit): RoutesApi {
        return retrofit.create(RoutesApi::class.java)
    }
}
